### ISSUE TITLE
quetion

### ISSUE THREAD

**Issue by syf980302** [rohin-dasari/Tensorflow-Knowledge-Distillation#1]
Hello! I want to ask why unused import statement 'datasets' is displayed; Can I delete datasets directly?

Excuse me, thank you.

**Comment by rohin-dasari** [comment]
Are you talking about ```from tensorflow.keras import datasets, layers, models``` from `distiller.py`? I believe that the `datasets` module imported there is only used to get the mnist data used in the demo. If you're using a dataset that isn't a keras dataset provided by tensorflow, you don't really need that import.

**Comment by syf980302** [comment]
Thanks！

**Comment by syf980302** [comment]
Hello, I have a question for you. I want to ask how you call out the architecture of the teacher model. I tried many methods here, but I couldn't get it. Thank you very much.

**Comment by rohin-dasari** [comment]
Closing this issue, since you opened another one for this other question
